"""
Per-language enrichment rule packs.

This module is the **single place** language-specific enrichment data lives. Each
supported language contributes one :class:`LangPack` (keyed by ISO 639-1 code) and
nothing else in the codebase hardcodes a natural language. ``enrichment.py`` compiles
these packs into matchers (cached per language); ``retrieval.py`` reads ``snowball_name``
for optional stemming.

Adding a 5th language is a **data-only** change: append one ``LangPack(...)`` literal to
:data:`_PACKS` and its code to :data:`SUPPORTED_LANGUAGES`. No logic anywhere else needs
to change — the classifiers, extractors, tokenizers and detector are all
language-parameterised, and the Unicode ``\\w`` tokenizers already cover Latin-script
diacritics.

Design notes (mirroring ``enrichment.py``'s contract):
- ``section_rules`` / ``genre_title_rules`` keywords are matched with a **leading word
  boundary only** (``\\b`` before the keyword, none after), so a keyword matches at a word
  *start* and still catches inflections/compounds — e.g. German ``"sicherheit"`` matches
  ``"Sicherheitskonzept"``; English ``"config"`` matches ``"configuration"``. Keep keywords
  specific so they are not a prefix of an unrelated word.
- Section-rule **order matters** (first match wins); keep the :class:`SectionType` ordering
  identical across languages.
- This module imports only :mod:`.models` (pure enums) — it stays I/O-free so
  ``enrichment.py`` can keep its no-I/O guardrail.
"""

from __future__ import annotations

from dataclasses import dataclass

from .models import Genre, SectionType

# Tech/protocol acronyms are language-neutral; every language's SECURITY/API lists
# share them so a "JWT"/"OAuth" heading classifies the same regardless of prose language.
_SHARED_SECURITY_ACRONYMS = ["token", "rbac", "jwt", "oauth", "saml", "tls"]
# Admonition callout words frequently used verbatim (``> [!NOTE]``) even in non-English
# docs, so every pack folds the English labels in alongside its own.
_EN_ADMONITIONS = ("note", "warning", "tip", "important", "caution", "info", "danger", "attention")


@dataclass(frozen=True)
class LangPack:
    """All language-specific enrichment data for one language.

    Stored as plain data (lists/sets/pattern bodies); ``enrichment.py`` compiles the
    regex matchers from it, cached per language.
    """

    code: str
    section_rules: dict[SectionType, list[str]]
    genre_title_rules: dict[Genre, list[str]]
    # Inner alternation body for strong obligation modals (POLICY genre signal); compiled
    # as ``\b(?:<modal_pattern>)\b`` with IGNORECASE. Weak modals (en "should", de "soll")
    # are intentionally excluded — too common in ordinary explanation.
    modal_pattern: str
    imperative_verbs: frozenset[str]
    rake_stopwords: frozenset[str]
    admonition_labels: tuple[str, ...]
    # snowballstemmer language name (en→"english", …) or None if unsupported.
    snowball_name: str | None


# ── English (the baseline — values are byte-identical to the legacy enrichment globals) ──

_EN = LangPack(
    code="en",
    section_rules={
        SectionType.DECISION: [
            "decision",
            "adr",
            "rationale",
            "reasoning",
            "propose",
            "proposal",
            "chosen",
            "why",
        ],
        SectionType.ALTERNATIVE: [
            "alternative",
            "options considered",
            "option considered",
            "consideration",
            "considered",
            "other options",
            "rejected",
        ],
        SectionType.TRADEOFF: [
            "pro argument",
            "con argument",
            "pros and cons",
            "pros/cons",
            "trade-off",
            "tradeoff",
        ],
        SectionType.CONSEQUENCE: [
            "consequence",
            "downside",
            "drawback",
            "impact",
            "affected",
            "side effect",
            "migration effort",
            "risk",
        ],
        SectionType.DONE_CRITERIA: [
            "definition of done",
            "defines this",
            "acceptance criteria",
            "success criteria",
        ],
        SectionType.SECURITY: [
            "security",
            "auth",
            "authentication",
            "authorization",
            "permission",
            "rbac",
            "token",
            "encryption",
            "tls",
            "certificate",
            "secret",
            "credentials",
            "jwt",
            "oauth",
            "saml",
        ],
        SectionType.DATA_MODEL: [
            "data model",
            "entity schema",
            "entity",
            "database",
            "table",
            "field",
            "dto",
            "event schema",
            "message format",
            "payload schema",
        ],
        SectionType.OVERVIEW: [
            "overview",
            "introduction",
            "purpose",
            "summary",
            "background",
            "context",
            "about",
            "scope",
            "goals",
            "objectives",
            "motivation",
            "problem",
        ],
        SectionType.ARCHITECTURE: [
            "architecture",
            "system design",
            "components",
            "structure",
            "high level",
            "high-level",
            "diagram",
            "topology",
            "modules",
        ],
        SectionType.API: [
            "api",
            "interface",
            "endpoint",
            "contract",
            "schema",
            "rest",
            "grpc",
            "openapi",
            "swagger",
            "request",
            "response",
            "payload",
            "routes",
            "operations",
        ],
        SectionType.DEPLOYMENT: [
            "deployment",
            "infrastructure",
            "config",
            "configuration",
            "environment",
            "kubernetes",
            "docker",
            "helm",
            "ci/cd",
            "pipeline",
            "release",
            "rollout",
        ],
    },
    genre_title_rules={
        Genre.GLOSSARY: ["glossary", "definitions", "terminology", "terms", "nomenclature"],
        Genre.FAQ: ["faq", "frequently asked", "q&a", "questions and answers"],
        Genre.HOWTO: [
            "how to",
            "how-to",
            "howto",
            "tutorial",
            "walkthrough",
            "step-by-step",
            "step by step",
            "getting started",
            "installation",
            "setup",
            "procedure",
            "runbook",
        ],
        Genre.POLICY: [
            "policy",
            "policies",
            "guideline",
            "guidelines",
            "compliance",
            "code of conduct",
            "terms of service",
            "acceptable use",
        ],
    },
    modal_pattern=(
        r"must(?:\s+not)?|shall(?:\s+not)?|may\s+not|required|prohibited|mandatory|forbidden"
    ),
    imperative_verbs=frozenset(
        {
            "install",
            "run",
            "click",
            "open",
            "create",
            "set",
            "configure",
            "add",
            "remove",
            "select",
            "enter",
            "navigate",
            "choose",
            "download",
            "save",
            "deploy",
            "build",
            "start",
            "stop",
            "restart",
            "copy",
            "paste",
            "update",
            "verify",
            "check",
            "ensure",
            "define",
            "call",
            "import",
            "export",
            "execute",
            "launch",
            "type",
            "press",
            "go",
            "visit",
            "enable",
            "disable",
            "apply",
            "edit",
            "delete",
            "push",
            "pull",
            "commit",
            "clone",
            "login",
            "register",
            "upload",
            "submit",
            "review",
            "confirm",
            "repeat",
            "close",
            "find",
            "replace",
        }
    ),
    rake_stopwords=frozenset(
        {
            "a",
            "an",
            "the",
            "and",
            "or",
            "but",
            "nor",
            "so",
            "yet",
            "for",
            "of",
            "to",
            "in",
            "on",
            "at",
            "by",
            "as",
            "is",
            "are",
            "was",
            "were",
            "be",
            "been",
            "being",
            "am",
            "it",
            "its",
            "this",
            "that",
            "these",
            "those",
            "with",
            "from",
            "into",
            "onto",
            "about",
            "over",
            "under",
            "between",
            "through",
            "during",
            "before",
            "after",
            "above",
            "below",
            "up",
            "down",
            "out",
            "off",
            "if",
            "then",
            "else",
            "than",
            "when",
            "while",
            "where",
            "which",
            "who",
            "whom",
            "whose",
            "what",
            "why",
            "how",
            "all",
            "any",
            "both",
            "each",
            "few",
            "more",
            "most",
            "other",
            "some",
            "such",
            "no",
            "not",
            "only",
            "own",
            "same",
            "too",
            "very",
            "can",
            "will",
            "just",
            "should",
            "now",
            "also",
            "we",
            "you",
            "they",
            "he",
            "she",
            "i",
            "our",
            "your",
            "their",
            "his",
            "her",
            "them",
            "us",
            "me",
            "my",
            "do",
            "does",
            "did",
            "done",
            "have",
            "has",
            "had",
            "having",
            "would",
            "could",
            "may",
            "might",
            "must",
            "shall",
            "there",
            "here",
            "because",
            "via",
            "per",
            "etc",
        }
    ),
    admonition_labels=_EN_ADMONITIONS,
    snowball_name="english",
)


# ── German ───────────────────────────────────────────────────────────────────────────────

_DE = LangPack(
    code="de",
    section_rules={
        SectionType.DECISION: [
            "entscheidung",
            "beschluss",
            "begründung",
            "vorschlag",
            "gewählt",
            "warum",
            "adr",
        ],
        SectionType.ALTERNATIVE: [
            "alternative",
            "option",  # matches "optionen", "optionale ..."
            "abgelehnt",
            "verworfen",
            "andere optionen",
            "erwogene",
        ],
        SectionType.TRADEOFF: [
            "vor- und nachteile",
            "vor und nachteile",
            "vorteile und nachteile",
            "pro und contra",
            "pro/contra",
            "kompromiss",
            "abwägung",
        ],
        SectionType.CONSEQUENCE: [
            "konsequenz",
            "auswirkung",
            "nachteil",  # bare "Nachteile" → consequence (tradeoff uses multi-word phrases)
            "risiko",
            "betroffen",
            "migrationsaufwand",
            "nebeneffekt",
        ],
        SectionType.DONE_CRITERIA: [
            "abnahmekriterien",
            "akzeptanzkriterien",
            "erfolgskriterien",
            "fertigstellungskriterien",
            "definition of done",
        ],
        SectionType.SECURITY: [
            "sicherheit",
            "authentifizierung",
            "autorisierung",
            "berechtigung",
            "verschlüsselung",
            "zertifikat",
            "geheimnis",
            "anmeldedaten",
            *_SHARED_SECURITY_ACRONYMS,
        ],
        SectionType.DATA_MODEL: [
            "datenmodell",
            "entität",
            "datenbank",
            "tabelle",
            "feld",
            "datenschema",
            "schema",
            "nachrichtenformat",
            "nutzlast",
            "dto",
        ],
        SectionType.OVERVIEW: [
            "überblick",
            "übersicht",
            "einführung",
            "einleitung",
            "zweck",
            "zusammenfassung",
            "hintergrund",
            "kontext",
            "ziel",
            "umfang",
            "geltungsbereich",
            "motivation",
            "problem",
        ],
        SectionType.ARCHITECTURE: [
            "architektur",
            "systemdesign",
            "systementwurf",
            "komponenten",
            "struktur",  # \bstruktur does NOT match mid-word "Infrastruktur"
            "aufbau",
            "topologie",
            "module",
        ],
        SectionType.API: [
            "schnittstelle",
            "api",
            "endpunkt",
            "vertrag",
            "anfrage",
            "antwort",
            "rest",
            "grpc",
            "openapi",
            "swagger",
            "routen",
        ],
        SectionType.DEPLOYMENT: [
            "bereitstellung",
            "infrastruktur",
            "konfiguration",
            "umgebung",
            "kubernetes",
            "docker",
            "helm",
            "ci/cd",
            "pipeline",
            "release",
            "auslieferung",
            "freigabe",
            "rollout",
            "betrieb",
        ],
    },
    genre_title_rules={
        Genre.GLOSSARY: ["glossar", "definitionen", "begriffe", "fachbegriffe", "terminologie"],
        Genre.FAQ: ["faq", "häufige fragen", "häufig gestellte fragen", "fragen und antworten"],
        Genre.HOWTO: [
            "anleitung",
            "tutorial",
            "schritt für schritt",
            "schritt-für-schritt",
            "erste schritte",
            "installation",
            "einrichtung",
            "vorgehen",
            "handbuch",
            "leitfaden",
        ],
        Genre.POLICY: [
            "richtlinie",
            "richtlinien",
            "vorschrift",
            "vorschriften",
            "compliance",
            "verhaltenskodex",
            "nutzungsbedingungen",
            "konformität",
        ],
    },
    modal_pattern=(
        r"muss|müssen|darf\s+nicht|dürfen\s+nicht|soll\s+nicht|sollen\s+nicht|"
        r"erforderlich|verboten|untersagt|verpflichtend|obligatorisch|zwingend"
    ),
    imperative_verbs=frozenset(
        {
            "installieren",
            "installiere",
            "ausführen",
            "führe",
            "starten",
            "starte",
            "stoppen",
            "stoppe",
            "öffnen",
            "öffne",
            "klicken",
            "klicke",
            "erstellen",
            "erstelle",
            "hinzufügen",
            "füge",
            "entfernen",
            "entferne",
            "auswählen",
            "wähle",
            "eingeben",
            "gib",
            "navigieren",
            "navigiere",
            "herunterladen",
            "lade",
            "speichern",
            "speichere",
            "konfigurieren",
            "konfiguriere",
            "aktualisieren",
            "aktualisiere",
            "prüfen",
            "prüfe",
            "überprüfen",
            "überprüfe",
            "definieren",
            "definiere",
            "aufrufen",
            "rufe",
            "importieren",
            "importiere",
            "exportieren",
            "exportiere",
            "aktivieren",
            "aktiviere",
            "deaktivieren",
            "deaktiviere",
            "bearbeiten",
            "bearbeite",
            "löschen",
            "lösche",
            "kopieren",
            "kopiere",
            "einfügen",
            "wiederholen",
            "wiederhole",
            "schließen",
            "schließe",
            "ersetzen",
            "ersetze",
            "anmelden",
            "registrieren",
            "hochladen",
            "absenden",
            "senden",
            "bestätigen",
            "bestätige",
            "wechseln",
            "setzen",
            "setze",
            "drücken",
            "drücke",
            "gehen",
            "gehe",
            "besuchen",
            "anwenden",
            "bauen",
            "baue",
            "bereitstellen",
            "stelle",
        }
    ),
    rake_stopwords=frozenset(
        {
            "der",
            "die",
            "das",
            "den",
            "dem",
            "des",
            "ein",
            "eine",
            "einen",
            "einem",
            "einer",
            "eines",
            "und",
            "oder",
            "aber",
            "sondern",
            "denn",
            "nicht",
            "kein",
            "keine",
            "mit",
            "von",
            "vom",
            "zu",
            "zum",
            "zur",
            "für",
            "auf",
            "aus",
            "an",
            "am",
            "bei",
            "beim",
            "nach",
            "über",
            "unter",
            "vor",
            "hinter",
            "neben",
            "zwischen",
            "durch",
            "gegen",
            "ohne",
            "um",
            "ist",
            "sind",
            "war",
            "waren",
            "sein",
            "bin",
            "bist",
            "wird",
            "werden",
            "wurde",
            "wurden",
            "kann",
            "können",
            "muss",
            "müssen",
            "soll",
            "sollen",
            "darf",
            "dürfen",
            "will",
            "wollen",
            "hat",
            "haben",
            "hatte",
            "hatten",
            "als",
            "wie",
            "wenn",
            "dann",
            "also",
            "auch",
            "nur",
            "schon",
            "noch",
            "sehr",
            "mehr",
            "viel",
            "diese",
            "dieser",
            "dieses",
            "diesem",
            "diesen",
            "es",
            "sie",
            "er",
            "wir",
            "ihr",
            "ich",
            "du",
            "man",
            "sich",
            "mein",
            "dein",
            "unser",
            "im",
            "in",
            "ins",
            "dass",
            "ob",
            "weil",
            "damit",
            "hier",
            "dort",
            "da",
            "so",
        }
    ),
    admonition_labels=(
        "hinweis",
        "warnung",
        "tipp",
        "wichtig",
        "achtung",
        "vorsicht",
        "gefahr",
        "anmerkung",
        *_EN_ADMONITIONS,
    ),
    snowball_name="german",
)


# ── French ───────────────────────────────────────────────────────────────────────────────

_FR = LangPack(
    code="fr",
    section_rules={
        SectionType.DECISION: [
            "décision",
            "justification",
            "proposition",
            "choisi",
            "choix retenu",
            "pourquoi",
            "adr",
        ],
        SectionType.ALTERNATIVE: [
            "alternative",
            "option",
            "options envisagées",
            "rejeté",
            "rejetée",
            "écarté",
            "autres options",
            "envisagé",
        ],
        SectionType.TRADEOFF: [
            "avantages et inconvénients",
            "pour et contre",
            "compromis",
            "arbitrage",
        ],
        SectionType.CONSEQUENCE: [
            "conséquence",
            "impact",
            "inconvénient",
            "risque",
            "affecté",
            "effet de bord",
            "effort de migration",
        ],
        SectionType.DONE_CRITERIA: [
            "critères d'acceptation",
            "critères de réussite",
            "critères de validation",
            "definition of done",
        ],
        SectionType.SECURITY: [
            "sécurité",
            "authentification",
            "autorisation",
            "permission",
            "chiffrement",
            "certificat",
            "secret",
            "identifiants",
            *_SHARED_SECURITY_ACRONYMS,
        ],
        SectionType.DATA_MODEL: [
            "modèle de données",
            "entité",
            "base de données",
            "table",
            "champ",
            "schéma d'entité",
            "schéma",
            "format de message",
            "charge utile",
            "dto",
        ],
        SectionType.OVERVIEW: [
            "aperçu",
            "vue d'ensemble",
            "introduction",
            "objectif",
            "objectifs",
            "résumé",
            "contexte",
            "portée",
            "motivation",
            "présentation",
            "but",
            "problème",
        ],
        SectionType.ARCHITECTURE: [
            "architecture",
            "conception du système",
            "conception",
            "composants",
            "structure",
            "topologie",
            "modules",
        ],
        SectionType.API: [
            "interface",
            "api",
            "point de terminaison",
            "endpoint",
            "contrat",
            "requête",
            "réponse",
            "rest",
            "grpc",
            "openapi",
            "swagger",
            "routes",
        ],
        SectionType.DEPLOYMENT: [
            "déploiement",
            "infrastructure",
            "configuration",
            "environnement",
            "kubernetes",
            "docker",
            "helm",
            "ci/cd",
            "pipeline",
            "release",
            "mise en production",
            "livraison",
            "rollout",
        ],
    },
    genre_title_rules={
        Genre.GLOSSARY: ["glossaire", "définitions", "terminologie", "termes", "lexique"],
        Genre.FAQ: ["faq", "questions fréquentes", "foire aux questions", "questions et réponses"],
        Genre.HOWTO: [
            "comment",
            "tutoriel",
            "guide",
            "étape par étape",
            "pas à pas",
            "prise en main",
            "installation",
            "mise en place",
            "procédure",
            "manuel",
        ],
        Genre.POLICY: [
            "politique",
            "directive",
            "directives",
            "règle",
            "règles",
            "conformité",
            "code de conduite",
            "conditions d'utilisation",
        ],
    },
    modal_pattern=(
        r"doit|doivent|ne\s+doit\s+pas|ne\s+doivent\s+pas|requis|requise|"
        r"interdit|interdite|obligatoire|prohibé"
    ),
    imperative_verbs=frozenset(
        {
            "installer",
            "installez",
            "exécuter",
            "exécutez",
            "lancer",
            "lancez",
            "ouvrir",
            "ouvrez",
            "cliquer",
            "cliquez",
            "créer",
            "créez",
            "ajouter",
            "ajoutez",
            "supprimer",
            "supprimez",
            "sélectionner",
            "sélectionnez",
            "saisir",
            "saisissez",
            "entrer",
            "entrez",
            "naviguer",
            "naviguez",
            "télécharger",
            "téléchargez",
            "enregistrer",
            "enregistrez",
            "sauvegarder",
            "configurer",
            "configurez",
            "mettre",
            "vérifier",
            "vérifiez",
            "définir",
            "définissez",
            "appeler",
            "importer",
            "exporter",
            "activer",
            "activez",
            "désactiver",
            "modifier",
            "modifiez",
            "éditer",
            "copier",
            "copiez",
            "coller",
            "répéter",
            "fermer",
            "remplacer",
            "connecter",
            "inscrire",
            "téléverser",
            "envoyer",
            "envoyez",
            "soumettre",
            "confirmer",
            "choisir",
            "choisissez",
            "appuyer",
            "appuyez",
            "presser",
            "aller",
            "visiter",
            "appliquer",
            "construire",
            "déployer",
            "démarrer",
            "arrêter",
            "redémarrer",
        }
    ),
    rake_stopwords=frozenset(
        {
            "le",
            "la",
            "les",
            "un",
            "une",
            "des",
            "du",
            "de",
            "d",
            "l",
            "et",
            "ou",
            "mais",
            "donc",
            "car",
            "ne",
            "pas",
            "ni",
            "à",
            "au",
            "aux",
            "en",
            "dans",
            "sur",
            "sous",
            "par",
            "pour",
            "avec",
            "sans",
            "vers",
            "chez",
            "entre",
            "est",
            "sont",
            "était",
            "étaient",
            "être",
            "suis",
            "es",
            "sera",
            "seront",
            "a",
            "ont",
            "avait",
            "avaient",
            "avoir",
            "fait",
            "peut",
            "peuvent",
            "doit",
            "doivent",
            "ce",
            "cet",
            "cette",
            "ces",
            "son",
            "sa",
            "ses",
            "leur",
            "leurs",
            "notre",
            "nos",
            "votre",
            "vos",
            "mon",
            "ma",
            "mes",
            "ton",
            "ta",
            "tes",
            "il",
            "elle",
            "ils",
            "elles",
            "nous",
            "vous",
            "je",
            "tu",
            "on",
            "se",
            "qui",
            "que",
            "quoi",
            "dont",
            "où",
            "quand",
            "comme",
            "si",
            "plus",
            "moins",
            "très",
            "aussi",
            "encore",
            "déjà",
            "ici",
            "là",
            "ainsi",
        }
    ),
    admonition_labels=(
        "note",
        "avertissement",
        "astuce",
        "important",
        "attention",
        "prudence",
        "danger",
        "remarque",
        *_EN_ADMONITIONS,
    ),
    snowball_name="french",
)


# ── Italian ──────────────────────────────────────────────────────────────────────────────

_IT = LangPack(
    code="it",
    section_rules={
        SectionType.DECISION: [
            "decisione",
            "motivazione",
            "giustificazione",
            "proposta",
            "scelto",
            "scelta",
            "perché",
            "adr",
        ],
        SectionType.ALTERNATIVE: [
            "alternativa",
            "alternative",
            "opzione",
            "opzioni considerate",
            "respinto",
            "scartato",
            "altre opzioni",
            "considerato",
        ],
        SectionType.TRADEOFF: [
            "vantaggi e svantaggi",
            "pro e contro",
            "compromesso",
        ],
        SectionType.CONSEQUENCE: [
            "conseguenza",
            "impatto",
            "svantaggio",
            "rischio",
            "interessato",
            "effetto collaterale",
            "sforzo di migrazione",
        ],
        SectionType.DONE_CRITERIA: [
            "criteri di accettazione",
            "criteri di successo",
            "criteri di completamento",
            "definition of done",
        ],
        SectionType.SECURITY: [
            "sicurezza",
            "autenticazione",
            "autorizzazione",
            "permesso",
            "cifratura",
            "crittografia",
            "certificato",
            "segreto",
            "credenziali",
            *_SHARED_SECURITY_ACRONYMS,
        ],
        SectionType.DATA_MODEL: [
            "modello dati",
            "modello di dati",
            "entità",
            "database",
            "tabella",
            "campo",
            "schema entità",
            "schema",
            "formato messaggio",
            "payload",
            "dto",
        ],
        SectionType.OVERVIEW: [
            "panoramica",
            "introduzione",
            "scopo",
            "sintesi",
            "riassunto",
            "contesto",
            "ambito",
            "obiettivo",
            "obiettivi",
            "motivazione",
            "presentazione",
            "problema",
        ],
        SectionType.ARCHITECTURE: [
            "architettura",
            "progettazione del sistema",
            "componenti",
            "struttura",
            "topologia",
            "moduli",
        ],
        SectionType.API: [
            "interfaccia",
            "api",
            "endpoint",
            "contratto",
            "richiesta",
            "risposta",
            "rest",
            "grpc",
            "openapi",
            "swagger",
            "rotte",
        ],
        SectionType.DEPLOYMENT: [
            "distribuzione",
            "infrastruttura",
            "configurazione",
            "ambiente",
            "kubernetes",
            "docker",
            "helm",
            "ci/cd",
            "pipeline",
            "rilascio",
            "messa in produzione",
            "rollout",
            "implementazione",
        ],
    },
    genre_title_rules={
        Genre.GLOSSARY: ["glossario", "definizioni", "terminologia", "termini", "lessico"],
        Genre.FAQ: ["faq", "domande frequenti", "domande e risposte"],
        Genre.HOWTO: [
            "come",
            "tutorial",
            "guida",
            "passo dopo passo",
            "passo per passo",
            "per iniziare",
            "installazione",
            "procedura",
            "manuale",
        ],
        Genre.POLICY: [
            "politica",
            "direttiva",
            "direttive",
            "linee guida",
            "regola",
            "regole",
            "conformità",
            "codice di condotta",
            "termini di servizio",
        ],
    },
    modal_pattern=(
        r"deve|devono|non\s+deve|non\s+devono|richiesto|richiesta|"
        r"vietato|vietata|obbligatorio|obbligatoria|proibito"
    ),
    imperative_verbs=frozenset(
        {
            "installare",
            "installa",
            "eseguire",
            "esegui",
            "avviare",
            "avvia",
            "aprire",
            "apri",
            "cliccare",
            "clicca",
            "creare",
            "crea",
            "aggiungere",
            "aggiungi",
            "rimuovere",
            "rimuovi",
            "selezionare",
            "seleziona",
            "inserire",
            "inserisci",
            "immettere",
            "navigare",
            "naviga",
            "scaricare",
            "scarica",
            "salvare",
            "salva",
            "configurare",
            "configura",
            "aggiornare",
            "aggiorna",
            "verificare",
            "verifica",
            "controllare",
            "controlla",
            "definire",
            "definisci",
            "chiamare",
            "chiama",
            "importare",
            "importa",
            "esportare",
            "esporta",
            "abilitare",
            "abilita",
            "disabilitare",
            "disabilita",
            "modificare",
            "modifica",
            "eliminare",
            "elimina",
            "copiare",
            "copia",
            "incollare",
            "incolla",
            "ripetere",
            "ripeti",
            "chiudere",
            "chiudi",
            "sostituire",
            "sostituisci",
            "accedere",
            "accedi",
            "registrare",
            "registra",
            "caricare",
            "carica",
            "inviare",
            "invia",
            "confermare",
            "conferma",
            "scegliere",
            "scegli",
            "premere",
            "premi",
            "andare",
            "vai",
            "visitare",
            "visita",
            "applicare",
            "applica",
            "costruire",
            "distribuire",
            "distribuisci",
        }
    ),
    rake_stopwords=frozenset(
        {
            "il",
            "lo",
            "la",
            "i",
            "gli",
            "le",
            "un",
            "uno",
            "una",
            "di",
            "del",
            "dello",
            "della",
            "dei",
            "degli",
            "delle",
            "da",
            "dal",
            "e",
            "ed",
            "o",
            "ma",
            "però",
            "anche",
            "non",
            "né",
            "a",
            "al",
            "allo",
            "alla",
            "ai",
            "agli",
            "alle",
            "in",
            "nel",
            "nello",
            "nella",
            "su",
            "sul",
            "sullo",
            "sulla",
            "per",
            "con",
            "tra",
            "fra",
            "è",
            "sono",
            "era",
            "erano",
            "essere",
            "sia",
            "sarà",
            "saranno",
            "ha",
            "hanno",
            "aveva",
            "avevano",
            "avere",
            "può",
            "possono",
            "deve",
            "devono",
            "questo",
            "questa",
            "questi",
            "queste",
            "quello",
            "quella",
            "suo",
            "sua",
            "suoi",
            "sue",
            "loro",
            "nostro",
            "vostro",
            "mio",
            "tuo",
            "esso",
            "essa",
            "essi",
            "lui",
            "lei",
            "noi",
            "voi",
            "io",
            "tu",
            "che",
            "chi",
            "cui",
            "dove",
            "quando",
            "come",
            "se",
            "più",
            "meno",
            "molto",
            "già",
            "qui",
            "là",
            "così",
        }
    ),
    admonition_labels=(
        "nota",
        "avviso",
        "avvertenza",
        "suggerimento",
        "importante",
        "attenzione",
        "prudenza",
        "pericolo",
        *_EN_ADMONITIONS,
    ),
    snowball_name="italian",
)


_PACKS: dict[str, LangPack] = {
    "en": _EN,
    "de": _DE,
    "fr": _FR,
    "it": _IT,
}

#: ISO 639-1 codes with a rule pack. The language detector's allowed set and the CLI's
#: ``--lang`` choices derive from this, so adding a pack widens both automatically.
SUPPORTED_LANGUAGES: tuple[str, ...] = tuple(_PACKS)

DEFAULT_LANGUAGE = "en"


def normalize_language(language: str | None) -> str:
    """Return a supported ISO code for *language*, falling back to ``en``.

    Accepts e.g. ``"de"``, ``"DE"``, ``"de-DE"``, ``"de_AT"`` → ``"de"``. An unknown or
    empty value degrades to :data:`DEFAULT_LANGUAGE` so a typo never crashes enrichment.
    """
    if not language:
        return DEFAULT_LANGUAGE
    code = language.strip().lower().replace("_", "-").split("-", 1)[0]
    return code if code in _PACKS else DEFAULT_LANGUAGE


def get_lang_pack(language: str | None) -> LangPack:
    """Return the :class:`LangPack` for *language* (normalised, ``en`` fallback)."""
    return _PACKS[normalize_language(language)]
